### ISSUE TITLE
Showing "Transfer Successful" after invalid transactions

### ISSUE THREAD

**Issue by hayderkharrufa** [Keysign-Wallet/Keysign-Mobile#2]
**Describe the bug**
Keysign showing "Transfer Successful" page after invalid transactions.

**To Reproduce**
1. Go to 'Keysign Wallet page'.
2. Select an account that has more than 0 coins.
3. Go to 'Keysign Home page'.
3. Click on 'Send'.
3. Fill in the account number field with any valid account number.
4. Fill in the amount field with an amount larger than your account balance (ex: 9999999999).
5. Click on 'CONTINUE'.
6. See 'Transfer Successful' page.

**Expected behavior**
Showing "Transfer Failed" page after invalid transactions.

**Screenshots**

<img src="https://user-images.githubusercontent.com/38482276/144422406-da9e0cbe-3a1e-4da9-a3c3-f7bdd2d5aa5e.jpeg" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/38482276/144422433-7aad7f3c-3f26-4ef5-bf25-688a520fffe9.jpeg" width=30% height=30%>

**Smartphone:**
 - Device: OnePlus 3T
 - OS: Android 9.0.6
 - Version: 0.0.1

**Additional context**
(Tomi | 777#8409 on Discord) mentioned  that this is happening because of banks not throwing errors when they receive invalid transactions. So transactions must be prevented from going to the bank if the account doesn't have enough coins.

**Comment by mrbusysky** [comment]
We will look into it for sure and let you know.
